title: CogJS Documentation
description: Documentation for the CogJS cognitive science JavaScript library
theme: jekyll-theme-minimal

# GitHub Pages configuration
baseurl: "/cogjs"
url: "https://chenyu-psy.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from being published
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src/

# Navigation settings
include:
  - docs
