name: Deploy GitHub Pages

on:
  push:
    branches:
      - develop  # Set this to your main branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
        
      - name: Install dependencies
        working-directory: ./docs
        run: |
          gem install bundler
          bundle install
        
      - name: Build site
        working-directory: ./docs
        run: bundle exec jekyll build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          publish_branch: gh-pages
